class AppSrings {
  static String appName = 'IndiaLearner';
  static String appQuote = 'THE WAY TO ACHIEVE IT';

  static String selectCategory = 'Please select category';

  static String educatorAndTeacher = 'Educator/Teacher';

  static String fnameError = 'First name should not empty';
  static String lnameError = 'Last name should not empty';
  static String emailError = 'Email  should not empty';
  static String mobileError = 'Mobile number should not empty';
  static String passwordError = 'Password  should not empty';
  static String confiremPasswordError = 'Confirm password  should not empty';

  static String bioError = 'Bio should not empty';
  static String termsString =
      """<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>In this policy, the words &quot;we&quot;, &quot;our&quot;, and &quot;us&quot; refer to Indialearner and the privacy mechanism outlined identify personally identifiable or personal information that may be collected, how such information is used, and the choices You have regarding our use of this information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>In addition to the terms stated in Terms of Service provided under this Website/mobile application (together &ldquo;Platform&rdquo;), we are committed to protecting Your privacy. Only authorized representatives of Indialearner and on a need to know basis only use any information received from You and as consented by You. We constantly review our systems and data to secure Your personal information. In the event of any identified unauthorized use or disclosure of information or upon Your complaint, we will investigate any such complaint or such actions with a view to prosecuting and/or taking civil proceedings to recover damages against those responsible. Any User who does not agree with any provisions of this Privacy Policy and the Terms of Service is required to leave the Platform immediately. Should You disagree with this Policy (defined below) and still continue to access the Platform and provide Your personal information, Indialearner disclaim all the liabilities arising therefrom and it shall be assumed by Your continued use of the Platform that You have accepted the Policy and any other online terms and conditions available on the Platform.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>If any information You have provided or uploaded on the Platform violates the terms of this Policy, Indialearner may be required to delete such information upon informing You of the same and revoke Your access if required without incurring any liability to You.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>B. Applicability</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>This privacy policy (&ldquo;Policy&rdquo;) applies to all Users who access the Platform and are therefore required to read and understand the Policy before submitting any Personal Information (defined hereinafter). By submitting Personal Information, You are consenting to the use and processing of such information in accordance with this Policy. If You have inadvertently submitted any Personal Information to Indialearner prior to reading the Policy statements set out herein, or You do not agree with the manner in which the Personal Information is collected, stored or used, then You may access, modify and delete all information stored about You byv writing to us at . Indialearner is keeping personal data of the User, and every User is also entitled to require Indialearner to delete and destroy all such information (but not that of other Users).</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>This Policy applies to the Platform and any other services that are owned and operated by Indialearner. Third party websites may place their own cookies or other files on the Users&apos; computer, collect data or solicit personal information from the Users, for which Indialearner is not responsible or liable. Accordingly, Indialearner does not make any representations concerning the privacy practices or policies of such third parties or terms of use of such websites, nor does Indialearner guarantee the accuracy, integrity, or quality of the information, data, text, software, sound, photographs, graphics, videos, messages or other materials available on such websites. The inclusion or exclusion does not imply any endorsement by Indialearner of the website, the website&apos;s provider, or the information on the website. Indialearner encourages the User to read the privacy policies of each such website and the User understands that its solely such third party who is responsible to the User in this regard.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner has taken reasonable precautions as per applicable Indian law and implemented industry standards to treat Personal Information as confidential and to protect it from unauthorized access, improper use or disclosure, modification and unlawful destruction or accidental loss of the Personal Information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>C. Access</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>User are allowed to access the Platform, register for courses and avail services available with Indialearner . In order to have access to all the features and benefits on our Platform, a User is required to first create an account on our Platform. To create an account, a User is required to provide Personal Information as may be required during the time of registration. Other information requested on the registration page. Indialearner may, in future, include other optional requests for information from the User to help Indialearner to customize the Platform to deliver personalized information to the User. Without User&apos;s agreement, Indialearner will not share, rent or sell any Personal Information with third parties in any way other than what is disclosed in this Policy. Indialearner may keep records of telephone calls received and made for making enquiries, registered courses, feedback or other purposes for the purpose of rendering services effectively and efficiently.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>D. Personal Information</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>&ldquo;Personal Information&rdquo; shall mean the information which identifies the User, name, identification number, email address, age, gender, or phone number provided to Indialearner at the time of registration or any time thereafter. Personal information may include &ldquo;sensitive personal information or data&rdquo; as defined under the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and in this context, includes passwords or any financial account information provided by You during registration.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>We request You to not provide us with any Personal Information unless specifically requested by us. In such events, we bear no liability to such Personal Information provided by You.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>E. Automatic Information Collection</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Our system collects information that is sent over the internet without Your control. Some examples of the information we collect and analyse include the Internet protocol (IP) address used to connect Your computer to the internet; login; email; password; computer and connection information such as browser type and version, operating system, and platform; course enrolled history, which we sometimes aggregate with similar information from other users to create features, rep</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>F. Information Security</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>To protect the security of Your Personal information during transmission, we use Secure Sockets Layer (SSL) software, which encrypts information You input. To prevent unauthorized access to sensitive information, it is important for You to monitor those who have access to Your password and to Your computer, laptop or any other device through which Your account can be accessed. Be sure to sign off when finished while using a shared computer.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>However, please do note that given the nature of internet transactions, Indialearner does not take any responsibility for the transmission of information including Personal Information shared by You other than as set forth in this Policy. Any transmission of information on the internet is done at Your risk and shall not be responsible for the circumvention of the privacy settings or security measures either by You or any third-party.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>G. Use of your personal information</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>While availing our services You will provide access to Indialearner with Your Personal Information. If that information is wrong, You can request us to modify or delete the same. Indialearner will take all reasonable measures to ensure that the Personal Information is modified and used for rendering services to You and as otherwise in compliance with laws. When editing or deleting Personal Information, we may ask You to verify Your identity before we can act on Your request. Indialearner may at its discretion reject any request that is contrary to law, requires un-reasonable technical efforts. We do not assure that we will delete all residual copies and archives made by any third party without our knowledge and consent. We never retain Your Personal Information longer than it is required for the purposes of providing services through the Platform or as required by applicable Indian law. At times, we may also require to transfer Your Personal Information to third-party service providers, for instance to authorize transactions we may share Your financial data with such third-party providers. You hereby consent to Your transfer of Personal Information in all such instances. Indialearner carries out all such transfers strictly in accordance with law.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner shall use Your Personal Information to ensure services with respect to the Platform are presented to You in the most effective manner, to secure the Platform and make improvements, to carry out our obligations to You, and to communicate with You. The said communication can either be by calls, text or emails and for purposes which include transactional, service, or promotional calls or messages.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;'><span style='font-size:22px;font-family:"Arial","sans-serif";color:black;background:#FCFCFC;'>H. Exceptions</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Your Personal Information may be shared with third parties who have a need or authority to receive such information, if we have a good-faith belief that access, use, preservation or disclosure of the information is reasonably necessary to comply with (i) in response to any authority having to receive such information under law (ii) any order of court (iii) detect, prevent, or otherwise address fraud, security or technical issues (iv) protect against harm to the rights, property or safety of Indialearner, our users or the public as required or permitted by law.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;background:#FCFCFC;'><span style='font-size:22px;font-family:"Arial","sans-serif";'>User choices with regard to access of information</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner does not make any unsolicited calls or otherwise market any products or services, except for in relation to the purpose for which such information has been provided or taking any feedback, addressing any complaints, informing You about new features or free/paid courses. User shall not disclose their Personal Information to any third parties that is not authorised by Indialearner and verify the identity of such person who seek information. Indialearner will communicate with the Users through call, SMS, email or notices posted on the Platform or through any other means available, which shall include but not be limited to text, other forms of messaging, calls etc.&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner may, if You so choose, send direct mailers to You at the address given by You. You have the option to &apos;opt-out&apos; of this direct mailer by way of links provided at the bottom of each mailer.&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>All the information provided to Indialearner by You, You as a User confirms that the same including sensitive Personal Information, is true, accurate and voluntary. User has the right to withdraw information at any time, in accordance with the terms of this Policy and the Terms of Service.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;background:#FCFCFC;'><span style='font-size:22px;font-family:"Arial","sans-serif";'>Report, Analysis &amp; Confidentiality</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner may have to use Personal Information without reference to any persona or identity for research, statistical analysis improving the Platform of functionalities offered thereon and business intelligence purpose and may transfer such research, statistical or intelligence data in an aggregated or non-personally identifiable form to third parties and affiliates.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>All Indialearner employees and data processors, who have access to, and are associated with the processing of sensitive personal data or information, are obliged to respect the confidentiality of every User&apos;s sensitive personal data and information.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;background:#FCFCFC;'><span style='font-size:22px;font-family:"Arial","sans-serif";'>Sharing of Information</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner may also disclose or transfer User&apos;s personal and other information which a User provides, to another third party as part of reorganization or a sale of the assets of Indialearner corporation division or company. Any third party to which Indialearner transfers or sells its assets will have the right to continue to use the personal and other information that a User provide to us.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>To the extent necessary to provide Users with the services on the Platform, Indialearner may provide User&rsquo;s Personal Information to third party contractors who work on behalf of or with Indialearner to provide Users with such services, to help Indialearner communicate with Users or to maintain the Platform. Generally, these contractors do not have any independent right to share this information, however certain contractors who provide services on the Platform, including the providers of online communications services, online payment gateway services, will have rights to use and disclose the Personal Information collected in connection with the provision of these services in accordance with their own privacy policies.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Furthermore, please note that we cannot control the actions of other Users of the Platform with whom You may choose to share Your Personal Information, and any such actions on Your behalf shall be solely Your responsibility.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><span style='font-size:18px;line-height:107%;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;<br>&nbsp;</span></p>
<h3 style='margin-top:0in;margin-right:0in;margin-bottom:.25in;margin-left:0in;line-height:21.8pt;font-size:16px;font-family:"Calibri Light","sans-serif";color:#1F3763;font-weight:normal;background:#FCFCFC;'><span style='font-size:22px;font-family:"Arial","sans-serif";'>Revision of terms &amp; Grievance reporting</span></h3>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Indialearner may update or amend this Policy at any time, with or without advance notice. In the event there are significant changes in the way Indialearner treats User&apos;s personally identifiable information, Indialearner will display a notice on the Platform or send Users an email. Indialearner&apos;s current Policy to all information that Indialearner has about Users and their account.</span></p>
<p style='margin-right:0in;margin-left:0in;font-size:16px;font-family:"Times New Roman","serif";margin:0in;margin-bottom:.0001pt;line-height:17.35pt;background:#FCFCFC;'><span style='font-size:14px;font-family:"Arial","sans-serif";'>Notwithstanding the above, Indialearner shall not be required to notify the Users of any changes made to the privacy policy. Should You have any concern or reject the changes in the privacy policy You can refuse to accept the amendments and opt for withdrawing Your Personal Information by writing to us</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>&nbsp;</p>""";
}
